String.toLocaleString({
	"en": {
		
	},
	
	"ru": {
		"Log In": "Войти",
		"Log Out": "Выйти",
		"File": "Файл",
		"Languages": "Язык",
		"Edit": "Редактровать",
		"Copy": "Скопировать",
		"Paste": "Вставить",
		"Duplicate": "Дублировать",
		"Delete": "Удалить",
		"Save Copy": "Сохранить копию",
		"Publish": "Опубликовать",
		"Set Permissions": "Установить права",
		"Save Now": "Сохранить сейчас",	
		"Save to Inventory": "Сохранить в инвентарий",
		"Select": "Выбрать",
		"Select By Name": "Выбрать по имени",
		"Pick": "Выбрать",
		"Select None": "Снять выбор",
		"Select Scene": "Выбрать сцену",
		"Select by clicking": "Выбор по нажатию",
		"Transform": "Трансформировать",
		"Move": "Перемещать",
		"Rotate": "Вращать",
		"Scale": "Масштабировать",
		"Multi": "Все трансформации",
		"Local Coords": "Локальные координаты",
		"World Coords": "Глобальные координаты",
		"Snaps": "Сетка",
		"Large": "Большая",
		"Medium": "Средняя",
		"Small": "Маленькая",
		"Off": "Выключена",
		"Move Tool": "Перемещать",
		"Rotate Tool": "Вращать",
		"Scale Tool": "Масштабировать",
		"Use Local Coordinates": "Локальные координаты",
		"Use World Coordinates": "Глобальные координаты",
		"Camera": "Камера",
		"Focus Selected": "Фокурсировка на выбранном",
		"Share Camera View": "Разделить камеру",
		"Activate Camera": "Активировать камеру",
		"Default Cameras": "Камера по умолчанию",
		"Orbit": "Орбита",
		"Free": "Свободная",
		"Avatar View": "Вид от аватара",
		"Navigate": "Навигационная",
		"Fly": "Облет",
		"None": "Нет",
		"Hierarchy": "Иерархия",
		"Link": "Связать",
		"Unlink": "Удалить связь",
		"Select Parent": "Выбрать родителя",
		"Grouping": "Группировка",
		"Group": "Сгруппировать",
		"Ungroup": "Разгруппировать",
		"Open Group": "Открыть группу",
		"Close Group": "Закрыть группу",
		"Orbit Camera": "Камера орбита",
		"Navigation Camera": "Камера навигационная",
		"Free Camera": "Камера свободная",
		"Focus to selected object": "Сфокурсировать на выбранный объект",
		"First Person Camera": "Камера от первого лица",
		"Create": "Создать",
		"Primitives": "Примитивы",
		"Sphere": "Сфера",
		"Box": "Куб",
		"Plane": "Плоскость",
		"Cylinder": "Цилиндр",
		"Cone": "Конус",
		"Create Sphere": "Сфера",
		"Create Box": "Куб",
		"Create Plane": "Плоскость",
		"Create Cylinder": "Цилиндр",
		"Create Cone": "Конус",
		"Text": "Текст",
		"Torus": "Тор",
		"Shapes": "Фигуры",
		"Line": "Линия",
		"Circle": "Круг",
		"Star": "Звезда",
		"Rectangle": "Прямоугольник",
		"L Section": "L секция",
		"T Section": "T секция",
		"Modifiers": "Модификаторы",
		"Bend": "Сгибание",
		"Twist": "Скручивание",
		"Taper": "Сужение",
		"Perlin Noise": "Шум Перлина",
		"Simplex Noise": "Шум симплексный",
		"Offset": "Смещение",
		"Stretch": "Растяжение",
		"Push": "Вдавление",
		"UVMap": "UV карта",
		"Center Pivot": "Центр вращения",
		"Extrude": "Выдавливание",
		"Lathe": "Станок",
		"Behaviors": "Поведения",
		"New Behavior": "Новое поведение",
		"Rotator": "Поворотное устройство",
		"Orbit": "Орбита",
		"Hyper link": "Гиперссылка",
		"Hover label": "Знак на наведение",
		"Path Follow": "Следовать пути",
		"Clamp To Ground": "Заземлить",
		"LookAt": "Смотреть на..",
		"Seek": "Стремиться",
		"Dialog System":"Система диалогов",
		"Lights": "Свет",
		"Point": "Точечный",
		"Light": "Местный",
		"Directional": "Направленный",
		"Particles": "Система частиц",
		"Basic": "Простая",
		"Cameras": "Камеры",
		"Perspective": "Перспективная",
		"Orthographic (comming soon!)": "Ортографическая (скоро)",
		"Terrain": "Генератор земли",
		"Load Mesh URL": "Загрузить модель из ссылки",
		"Tools": "Инструменты",
		"Align": "Выравнять",
		"Block Painter": "Рисование блоками",
		"SnapMove": "Двигать по сетке",
		"Spline Tools": "Сплайн инструменты",
		"Windows": "Окна",
		"Chat": "Чат",
		"Users": "Пользователи",
		"Material Editor": "Редактор материалов",
		"Script Editor": "Редактор скриптов",
		"Object Properties": "Параметры объекта",
		"Models": "Модели",
		"Inventory": "Инвентарий",
		"Public Inventory": "Публичный инвентарий",
		"Show Hierarchy": "Показать иерархию объектов",
		"Rendering": "Рендеринг",
		"Toggle Wireframe": "Сетка",
		"Toggle Glyphs": "Показать иконки",
		"Toggle Sun Shadows": "Тени от солнца",
		"Toggle Full Screen": "Полный экран",
		"Toggle Stats": "Статистика",
		"Toggle Interpolation": "Интерполяция движений",
		"Batching": "",
		"Force Batch All": "",
		"Toggle Dynamic Batching": "",
		"Location": "Место",
		"Go to Position...": "Перейти в позицию...",
		"Go to Placemark...": "Перейти в место...",
		"Add Placemark...": "Добавить место...",
		"Move to ground": "Опуститься на землю",
		"Help": "Помощь",
		"About": "О программе",
		"Browse All Topics...": "Открыть все темы...",
		"Test Latency": "Тестировать сеть",
		"Show Users Window": "Окно пользователей",
		"Show Chat Window": "Чат",
		"Show Material Editor Window": "Редактор материалов",
		"Show Script Editor Window": "Редактор скриптов",
		"Show Object Properties Window": "Параметры объекта",
		"Show Inventory Window": "Инвентарий",
		"Show Hierarchy Window": "Иерархия объектов"
	}
});
 
